{
 "title": "SageMaker Cluster Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "user", "query": "armand,none" },
   { "name": "cluster", "query": "vgg-sagemaker-2node" },
   { "name": "host", "query": "algo-1,algo-2,algo-3,algo-4" },
   { "name": "network_interface", "query": "eth0,ecs-eth0" },
   { "name": "diskio_name", "query": "xvda1,xvdcz,xvdcz1" },
   { "name": "disk_name", "query": "xvda1" }
  ]
 },
 "panels": [
  {
   "title": "CPU - Percent In Use",
   "type": "graph",
   "description": "1 - cpu_idle",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 100 -  mean(\"usage_idle\") as \"in_use\" \nFROM \"cpu\"  \nWHERE  \"user\" =~ /$user/\nAND \"cluster\" =~ /$cluster/\nAND \"host\" =~ /$host/\nAND $timeFilter \nAND \"cpu\" = 'cpu-total'\nGROUP BY   time($__interval) , \"host\"\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network - Download/Upload Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(mean(bytes_recv), 1s)*8 as \"download rate\",\nderivative(mean(bytes_sent), 1s)*8 as \"upload rate\"\nFROM net \nWHERE  \"user\" =~ /$user/\nAND \"cluster\" =~ /$cluster/\nAND \"host\" =~ /$host/\nAND $timeFilter \nAND \"interface\"=~ /^$network_interface/ \nGROUP BY   time($__interval) , \"host\", \"interface\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"free\")\nFROM \"disk\"\nWHERE  \"user\" =~ /$user/\nAND \"cluster\" =~ /$cluster/\nAND \"host\" =~ /$host/\nAND \"device\" =~ /$disk_name/\nAND $timeFilter \nGROUP BY   time($__interval) , \"host\", \"device\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ip-172-31-79-15.ec2.internal" }
     ]
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"free\")\nFROM \"mem\"\nWHERE  \"user\" =~ /$user/\nAND \"cluster\" =~ /$cluster/\nAND \"host\" =~ /$host/\nAND $timeFilter \nGROUP BY   time($__interval) , \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk IO - Read Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"read_bytes\")\nFROM \"diskio\"\nWHERE  \"user\" =~ /$user/\nAND \"cluster\" =~ /$cluster/\nAND \"host\" =~ /$host/\nAND $timeFilter \nAND \"name\" =~ /$diskio_name/\nGROUP BY   time($__interval) , \"host\", \"name\"\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk IO - Write Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"write_bytes\")\nFROM \"diskio\"\nWHERE  \"user\" =~ /$user/\nAND \"cluster\" =~ /$cluster/\nAND \"host\" =~ /$host/\nAND $timeFilter \nAND \"name\" =~ /$diskio_name/\nGROUP BY   time($__interval) , \"host\", \"name\"\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}