#!/bin/bash
mpirun.real \
--allow-run-as-root \
--display-map \
--hostfile /hostfile \
-bind-to none -map-by slot \
-x LD_PRELOAD=/libchangehostname.so \
-x LD_LIBRARY_PATH \
-x PATH \
"$@"

# --tag-output \
